# Generated by Django 5.0.6 on 2024-07-07 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_x', models.FloatField(null=True)),
                ('center_y', models.FloatField(null=True)),
                ('width', models.FloatField(null=True)),
                ('height', models.FloatField(null=True)),
                ('score', models.IntegerField(null=True)),
                ('date', models.DateTimeField()),
                ('photo_file', models.CharField(max_length=200, null=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detections.family')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detections.zone')),
            ],
        ),
    ]
