# Generated by Django 5.0.7 on 2024-07-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
